---
- name: install/start httpd
  hosts: webservers 
  become: true 
  tasks:
  - name: install httpd
    package:
      name: "{{ apache_package }}"
      state: present

  - name: start/enable
    service:
      name: "{{ apache_service }}"
      state: started 
      enabled: true